---
# Controller Service
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nifcloud-hatoba-disk-csi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifcloud-hatoba-disk-csi-controller
  template:
    metadata:
      labels:
        app: nifcloud-hatoba-disk-csi-controller
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccount: nifcloud-hatoba-disk-csi-controller-sa
      priorityClassName: system-cluster-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: csi-driver
          image: ghcr.io/nifcloud/nifcloud-hatoba-disk-csi-driver
          imagePullPolicy: Always
          args :
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --mode=controller
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          envFrom:
          - secretRef:
              name: nifcloud-secret
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner
          args:
            - --csi-address=$(ADDRESS)
            - --feature-gates=Topology=true
            - --leader-election
            - --timeout=600s
            - --extra-create-metadata
            - --default-fstype=ext4
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher
          args:
            - --csi-address=$(ADDRESS)
            - --timeout=600s
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer
          args:
            - --csi-address=/csi/csi.sock
            - --timeout=600s
            - --handle-volume-inuse-error=false
            - --leader-election
            - --http-endpoint=:8080
          env:
            - name: PDCSI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe
          args:
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
