apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifcloud-hatoba-disk-csi-controller-sa
  namespace: kube-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifcloud-hatoba-disk-csi-node-sa
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-hatoba-disk-external-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-hatoba-disk-csi-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: nifcloud-hatoba-disk-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nifcloud-hatoba-disk-external-provisioner-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-hatoba-disk-external-attacher-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["get", "list", "watch", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-hatoba-disk-csi-attacher-binding
subjects:
  - kind: ServiceAccount
    name: nifcloud-hatoba-disk-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nifcloud-hatoba-disk-external-attacher-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-hatoba-disk-csi-node-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-hatoba-disk-csi-node-binding
subjects:
  - kind: ServiceAccount
    name: nifcloud-hatoba-disk-csi-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nifcloud-hatoba-disk-csi-node-role
  apiGroup: rbac.authorization.k8s.io
