name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: .go-version

      - name: Detect golangci-lint version
        id: golangci_lint_version
        run: echo version=$(grep "golangci/golangci-lint" Makefile | sed "s/^[^v0-9]*\(v[0-9]\.[0-9]*\).*/\1/") >> $GITHUB_OUTPUT

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ steps.golangci_lint_version.outputs.version }}
