name: Trivy Scanner for Latest Image

on:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner for latest image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          ignore-unfixed: true
          format: sarif
          output: results.sarif
          severity: HIGH,CRITICAL

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'results.sarif'
